FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04

ENV PYTHON_VERSION=3.7
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

WORKDIR /root
ENV HOME /root

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
    git \
    build-essential \
    software-properties-common \
    ca-certificates \
    wget \
    curl \
    htop \
    zip \
    unzip \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libreadline-dev \
    libffi-dev && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt install -y python3.7 python3-pip && \
    rm /usr/bin/python3 && \
    ln -s python3.7 /usr/bin/python3 && \
    python3 -V && \
    python3 -m pip --no-cache-dir install --upgrade pip setuptools && \
    ln -s $(which python3) /usr/local/bin/python

COPY ./requirements.txt ./requirements.txt

# Copies all the relevant files to the docker image
ADD ./src ./src
ADD ./data ./data

COPY ./requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

RUN  echo "/usr/local/cuda/compat" >> /etc/ld.so.conf.d/cuda-10-0.conf && \
    ldconfig

ENTRYPOINT ["python", "-u" "run.py"]
